version: '3'
services:
        web:
                image: beasts_flask
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8425:8425"
                volumes:
                        - ./instance:/app/instance
                restart: unless-stopped
